//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class fibonacciSequence {
    public static int findFibNums(int num) {
        int prev = 1;
        int next = 1;
        int sum = 0;
        int sumEvenFibs = 0;
        int i = 0;
        
        while (i < num) {
            sum = prev + next;
            
            if (sum % 2 == 0) {
                sumEvenFibs += sum;
            }
            
            prev = next; 
            next = sum;
            i++;
        } 
        return sumEvenFibs;
    } 
               
    public static void main(String[] args) {
        int fibonacciTerm = findFibNums(Integer.parseInt(args[0]));
        System.out.println(fibonacciTerm);
    }
}